[colors.primary]
background = '#12131c'
foreground = '#e3e1ef'

[colors.selection]
text = '#e3e1ef'
background = '#0f00ed'

[colors.cursor]
text = '#12131c'
cursor = '#bfc1ff'

[colors.normal]
black   = '#12131c'
red     = '#ff7294'
green   = '#7fff96'
yellow  = '#ffd872'
blue    = '#a9abf2'
magenta = '#3f4176'
cyan    = '#bfc1ff'
white   = '#eff0ff'

[colors.bright]
black   = '#9999a5'
red     = '#ff9fb6'
green   = '#a5ffb5'
yellow  = '#ffe6a5'
blue    = '#c8caff'
magenta = '#d2d3ff'
cyan    = '#e2e3ff'
white   = '#f8f8ff'
