[colors.primary]
background = '#fcf8ff'
foreground = '#1a1b25'

[colors.selection]
text = '#1a1b25'
background = '#e1e0ff'

[colors.cursor]
text = '#fcf8ff'
cursor = '#3a3bff'

[colors.normal]
black   = '#12131c'
red     = '#f21147'
green   = '#00bf22'
yellow  = '#ffb900'
blue    = '#3031ff'
magenta = '#bfc0ff'
cyan    = '#3a3bff'
white   = '#424347'

[colors.bright]
black   = '#d0d0d8'
red     = '#ff3969'
green   = '#26ff4d'
yellow  = '#ffb900'
blue    = '#6d4eff'
magenta = '#bfc0ff'
cyan    = '#9c9dff'
white   = '#f7f7ff'
